name: GitHub Actions Demo

on:

  push:

    branches:

      - main

    paths-ignore:

      - '.github/**'

  pull_request:

    branches:

      - main

  schedule:

    - cron: '15 6 * * 0'

  workflow_dispatch:




jobs:

  Build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v3




    - name: Output the name of the event that triggered the workflow

      run: |

        echo "🎉 The job was triggered by event: ${{ github.event_name }}"

        echo "Branch Name: ${{ github.ref_name }}"



    - name: List all files in the repository

      run: ls -R
